name: Daily Standup Report

on:
  schedule:
    - cron: '45 9 * * 1-5'  # 平日（週一到週五）UTC 09:45 = 台灣 17:45
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout work repo
        uses: actions/checkout@v4
        with:
          repository: w101-admin/W101-TalentSearchHub
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0   # 取得完整 commit 歷史

      - name: Get today's date
        id: date
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"

      - name: Get commit messages
        id: commits
        run: |
          since="$(date +'%Y-%m-%d')T00:00:00Z"
          until="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"  # 現在 UTC 時間
          logs=$(git log --since="$since" --until="$until" --pretty=format:'- %s')
          echo "LOGS<<EOF" >> $GITHUB_ENV
          echo "$logs" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Debug print commit logs
        run: |
          echo "------- Commit Logs -------"
          echo "${{ env.LOGS }}"

      - name: Call workflow endpoint
        run: |
          payload=$(jq -n \
            --arg date "${{ env.DATE }}" \
            --arg repo "w101-admin/W101-TalentSearchHub" \
            --arg author "github-actions" \
            --arg commit_logs "${{ env.LOGS }}" \
            --arg user "yc" \
            '{
              inputs: {
                date: $date,
                repo: $repo,
                author: $author,
                commit_logs: $commit_logs
              },
              response_mode: "blocking",
              user: $user
            }')

          curl -X POST 'http://44.243.2.205/v1/workflows/run' \
            --header 'Authorization: Bearer ${{ secrets.WORKFLOW_API_KEY }}' \
            --header 'Content-Type: application/json' \
            --data-raw "$payload"
